apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: binary-calculator
  template:
    metadata:
      labels:
        app: binary-calculator
    spec:
      containers:
      - name: binary-calculator-container
        image: your-registry/your-binary-calculator-image:latest
        ports:
        - containerPort: 8080

